//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountViewFollowersSuffix {
            get {
                return ResourceManager.GetString("AccountViewFollowersSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///    following に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountViewFollowingSuffix {
            get {
                return ResourceManager.GetString("AccountViewFollowingSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///    toots に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccountViewTootsSuffix {
            get {
                return ResourceManager.GetString("AccountViewTootsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorization code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorizationCode {
            get {
                return ResourceManager.GetString("AuthorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorization failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorizationFailedMessage {
            get {
                return ResourceManager.GetString("AuthorizationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorize {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorizeAppButtonText {
            get {
                return ResourceManager.GetString("AuthorizeAppButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully authorized! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorizedMessage {
            get {
                return ResourceManager.GetString("AuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot connect to the instance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialServerConnectionFailedMessage {
            get {
                return ResourceManager.GetString("InitialServerConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instance to connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstanceToConnect {
            get {
                return ResourceManager.GetString("InstanceToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderApp {
            get {
                return ResourceManager.GetString("MenuHeaderApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderAppSettings {
            get {
                return ResourceManager.GetString("MenuHeaderAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderTimeline {
            get {
                return ResourceManager.GetString("MenuHeaderTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderTimelineReload {
            get {
                return ResourceManager.GetString("MenuHeaderTimelineReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload _older toots に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderTimelineReloadOlder {
            get {
                return ResourceManager.GetString("MenuHeaderTimelineReloadOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Streaming に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderTimelineStreaming {
            get {
                return ResourceManager.GetString("MenuHeaderTimelineStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open authorization page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenAuthPageButtonText {
            get {
                return ResourceManager.GetString("OpenAuthPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Federated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAccountTabsFederated {
            get {
                return ResourceManager.GetString("SettingsAccountTabsFederated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account specific tabs to show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAccountTabsHeader {
            get {
                return ResourceManager.GetString("SettingsAccountTabsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAccountTabsHome {
            get {
                return ResourceManager.GetString("SettingsAccountTabsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAccountTabsLocal {
            get {
                return ResourceManager.GetString("SettingsAccountTabsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notifications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAccountTabsNotifications {
            get {
                return ResourceManager.GetString("SettingsAccountTabsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTabAccount {
            get {
                return ResourceManager.GetString("SettingsTabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsTabTabs {
            get {
                return ResourceManager.GetString("SettingsTabTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Boost に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuBoost {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuDelete {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Favourite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuFavourite {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuOpen {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open this _user&apos;s tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuOpenAccountTab {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuOpenAccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusesViewContextMenuReply {
            get {
                return ResourceManager.GetString("StatusesViewContextMenuReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toot! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TootButtonText {
            get {
                return ResourceManager.GetString("TootButtonText", resourceCulture);
            }
        }
    }
}
