//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Mastonet.Entities.AppRegistration AppRegistration {
            get {
                return ((global::Mastonet.Entities.AppRegistration)(this["AppRegistration"]));
            }
            set {
                this["AppRegistration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Mastonet.Entities.Auth Auth {
            get {
                return ((global::Mastonet.Entities.Auth)(this["Auth"]));
            }
            set {
                this["Auth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S(K(SII))(S(S(KS)K)(K(SII)))")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
            set {
                this["AppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfTabParameters xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <TabParameters xsi:type=""TimelineTabParameters"">
    <Name>Home</Name>
    <Type>Home</Type>
    <StreamingOnStartup>true</StreamingOnStartup>
  </TabParameters>
  <TabParameters xsi:type=""NotificationTabParameters"">
    <Name>Notifications</Name>
    <Type>Notifications</Type>
    <StreamingOnStartup>true</StreamingOnStartup>
  </TabParameters>
  <TabParameters xsi:type=""TimelineTabParameters"">
    <Name>Local</Name>
    <Type>Local</Type>
    <StreamingOnStartup>true</StreamingOnStartup>
  </TabParameters>
  <TabParameters xsi:type=""TimelineTabParameters"">
    <Name>Federated</Name>
    <Type>Federated</Type>
    <StreamingOnStartup>true</StreamingOnStartup>
  </TabParameters>
</ArrayOfTabParameters>")]
        public global::System.Collections.Generic.List<WpfApp2.Model.TabParameters> Tabs {
            get {
                return ((global::System.Collections.Generic.List<WpfApp2.Model.TabParameters>)(this["Tabs"]));
            }
            set {
                this["Tabs"] = value;
            }
        }
    }
}
